### ISSUE TITLE
[Bug] The Submit button does not display properly

### ISSUE THREAD

**Issue by NoverNobida** [urlhum/UrlHum#83]
**Describe the bug**
On the mobilebrowser, this button will overwrite the menu like this.

Maybe

```css
.input-group-prepend .btn {
 position:relative;
 z-index:2
}
```
should be

```css
.input-group-prepend .btn {
 position:relative;
 z-index:auto
}
```

**Screenshots**
![Snipaste_2020-04-28_15-13-13](https://user-images.githubusercontent.com/46912250/80458480-71aaad80-8963-11ea-8270-71b68863a5c2.png)

![Snipaste_2020-04-28_15-13-44](https://user-images.githubusercontent.com/46912250/80458598-9bfc6b00-8963-11ea-957f-0b449f09b5c1.png)
